name: fashion_star_shop
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  get: ^4.6.6
  test_api: ^0.6.1
  mocktail: ^1.0.3
  sqlite3_flutter_libs: ^0.5.20
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.1.0
  url_launcher: ^6.2.5
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  provider: ^6.1.2
  async_redux: ^23.0.0
  redux: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    # - assets/logos/
    - assets/icons/payment/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/users/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800